[project]
name = "transformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "ipython>=9.5.0",
    "psycopg2-binary>=2.9.10",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
