[project]
name = "mcpagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.68.0",
    "httpx>=0.28.1",
    "ipython>=9.5.0",
    "mcp[cli]>=1.14.1",
    "python-dotenv>=1.1.1",
]
